name: Greet first-time contributors

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hello! Since this is your first issue I would love to see you at our discord server for more info about the server! Regards GoldLand Staff!'' first issue'
        pr-message: 'Hello! Since this is your first pr I would love to see you at our discord server for more info about the server! Regards GoldLand Staff!'' first pr'
